name: Rust

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build no default features
      run: cargo build --verbose --no-default-features
    - name: Build all features
      run: cargo build --verbose --all-features
    - name: Run tests
      run: cargo test --verbose --all-features

  fuzz-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install cargo-fuzz
      run: cargo install -f cargo-fuzz --all-features
    - name: Install nightly
      run: rustup toolchain install nightly
    - name: Build
      run: cargo +nightly fuzz build --verbose --all-features

  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: rustup component add clippy
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
